-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text NOT NULL,
  url text NOT NULL,
  rating INTEGER DEFAULT '3',
  description text
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, rating, description)
values
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here'),
  ('Title A', 'https://www.google.com', '2', 'A description here');



  -- ('Title B', 'https://www.wikipedia.org', '2'),
  -- ('Title C', 'https://www.google.com', '5', 'A description'),
  -- ('Title D', 'https://www.facebook.com', '1', 'here'),
  -- ('Changing it up A', 'https://www.google.com', '2', 'A hamster here'),
  -- ('Thing thing', 'https://www.google.com', '3', 'A magic bean here'),
  -- ('That thing', 'https://www.sellasheep.com', '2', 'A dog here'),
  -- ('Title X', 'https://www.google.com', '5', 'A cat here'),
  -- ('Title Y', 'https://www.google.com', '2', 'A somethin here'),
  -- ('Title Z', 'https://www.google.com');
